/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    NFTStaking: {
      address: "0xb19b36b1456e65e3a6d514d3f715f204bd59f431",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "BASE_RESERVE_AMOUNT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "LOCK_PERIOD",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_NFTS_PER_MACHINE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SECONDS_PER_BLOCK",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SLASH_AMOUNT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "STAKING_TYPE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum StakingType",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "UPGRADE_INTERFACE_VERSION",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "_getMachineShares",
          inputs: [
            {
              name: "calcPoint",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "reservedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "addTokenToStake",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "calculateReleaseReward",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "releaseAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lockedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "calculateRewards",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "canUpgradeAddress",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "dailyRewardAmount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "dbcAIContract",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IDBCAIContract",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "forceUnStake",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getAllRewardInfo",
          inputs: [
            {
              name: "holder",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "availableRewardAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "canClaimAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lockedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getMachineIdsByStakeholder",
          inputs: [
            {
              name: "holder",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string[]",
              internalType: "string[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getMachineInfo",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "holder",
              type: "address",
              internalType: "address",
            },
            {
              name: "calcPoint",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "startAtTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "reservedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isOnline",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "isRegistered",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getReward",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRewardInfo",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "newRewardAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "canClaimAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lockedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getStakeHolder",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getaCalcPoint",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "holder2MachineIds",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "initialize",
          inputs: [
            {
              name: "_initialOwner",
              type: "address",
              internalType: "address",
            },
            {
              name: "_nftToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "_rewardToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "_dbcAIContract",
              type: "address",
              internalType: "address",
            },
            {
              name: "_slashToAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_projectName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "isStaking",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isStakingButOffline",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineId2LockedRewardDetail",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "totalAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lockTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "unlockTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineId2LockedRewardDetails",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "totalAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lockTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "unlockTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineId2MachineStatus",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum MachineStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineId2StakeInfos",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "holder",
              type: "address",
              internalType: "address",
            },
            {
              name: "startAtTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastClaimAtTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "calcPoint",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "reservedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "nftCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "gpuCount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineId2StakeUnitRewards",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "accumulated",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastAccumulatedPerShare",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineIsBlocked",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nftToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC1155",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "onERC1155BatchReceived",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "onERC1155Received",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingSlashedMachine",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "preCalculateRewards",
          inputs: [
            {
              name: "calcPoint",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "nftCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "reserveAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "projectName",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "proxiableUUID",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rewardStartAtTimestamp",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rewardToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rewardsPerCalcPoint",
          inputs: [],
          outputs: [
            {
              name: "accumulatedPerShare",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastUpdated",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setDBCAIContract",
          inputs: [
            {
              name: "addr",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setDLCClientWallets",
          inputs: [
            {
              name: "addrs",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setNftToken",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setRewardStartAt",
          inputs: [
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setRewardToken",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setUpgradeAddress",
          inputs: [
            {
              name: "addr",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "slashToAddress",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "stake",
          inputs: [
            {
              name: "stakeholder",
              type: "address",
              internalType: "address",
            },
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
            {
              name: "nftTokenIds",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "nftTokenIdBalances",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stakedMachineIds",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "totalAdjustUnit",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalCalcPoint",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalDistributedRewardAmount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalGpuCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalReservedAmount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalStakingGpuCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "unStake",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "unStakeByHolder",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "upgradeToAndCall",
          inputs: [
            {
              name: "newImplementation",
              type: "address",
              internalType: "address",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "validWalletAddress",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "version",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "event",
          name: "Claimed",
          inputs: [
            {
              name: "stakeholder",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "lockedRewardAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "moveToUserWalletAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "moveToReservedAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "paidSlash",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ExitStakingForOffline",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "holder",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Initialized",
          inputs: [
            {
              name: "version",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MachineRegistered",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MachineUnregistered",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MoveToReserveAmount",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "holder",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PaySlash",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "slashAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RenewRent",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "holder",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "rentFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ReportMachineFault",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "renter",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ReserveDLC",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RewardsPerCalcPointUpdate",
          inputs: [
            {
              name: "accumulatedPerShareBefore",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "accumulatedPerShareAfter",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Staked",
          inputs: [
            {
              name: "stakeholder",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "originCalcPoint",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "calcPoint",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StakedGPUType",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "gpuType",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Unstaked",
          inputs: [
            {
              name: "stakeholder",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "paybackReserveAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Upgraded",
          inputs: [
            {
              name: "implementation",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AddressEmptyCode",
          inputs: [
            {
              name: "target",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "AddressExists",
          inputs: [],
        },
        {
          type: "error",
          name: "CallerNotRentContract",
          inputs: [],
        },
        {
          type: "error",
          name: "CanNotUpgrade",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC1967InvalidImplementation",
          inputs: [
            {
              name: "implementation",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC1967NonPayable",
          inputs: [],
        },
        {
          type: "error",
          name: "FailedCall",
          inputs: [],
        },
        {
          type: "error",
          name: "GPUTypeNotMatch",
          inputs: [
            {
              name: "gpuType",
              type: "string",
              internalType: "string",
            },
          ],
        },
        {
          type: "error",
          name: "InvalidInitialization",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidNFTLength",
          inputs: [
            {
              name: "tokenIdLength",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "balanceLength",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "IsStaking",
          inputs: [],
        },
        {
          type: "error",
          name: "MachineIsStaking",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
        },
        {
          type: "error",
          name: "MachineNotOnlineOrRegistered",
          inputs: [],
        },
        {
          type: "error",
          name: "MachineNotRented",
          inputs: [],
        },
        {
          type: "error",
          name: "MachineNotStakeEnoughDBC",
          inputs: [],
        },
        {
          type: "error",
          name: "MachineNotStaked",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
        },
        {
          type: "error",
          name: "MachineRentedByUser",
          inputs: [],
        },
        {
          type: "error",
          name: "MachineStillRegistered",
          inputs: [],
        },
        {
          type: "error",
          name: "MemorySizeLessThan16G",
          inputs: [
            {
              name: "mem",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "NFTCountGreaterThan20",
          inputs: [],
        },
        {
          type: "error",
          name: "NotAdmin",
          inputs: [],
        },
        {
          type: "error",
          name: "NotInitializing",
          inputs: [],
        },
        {
          type: "error",
          name: "NotMachineOwner",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "NotMachineOwnerOrAdmin",
          inputs: [],
        },
        {
          type: "error",
          name: "NotPaidSlashBeforeClaim",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
            {
              name: "slashAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "NotStakeHolder",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
            {
              name: "currentAddress",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "RewardNotEnough",
          inputs: [],
        },
        {
          type: "error",
          name: "RewardNotStart",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "StakingInLongTerm",
          inputs: [],
        },
        {
          type: "error",
          name: "TimestampLessThanCurrent",
          inputs: [],
        },
        {
          type: "error",
          name: "TotalRateNotEq100",
          inputs: [],
        },
        {
          type: "error",
          name: "UUPSUnauthorizedCallContext",
          inputs: [],
        },
        {
          type: "error",
          name: "UUPSUnsupportedProxiableUUID",
          inputs: [
            {
              name: "slot",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroCalcPoint",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroNFTTokenIds",
          inputs: [],
        },
      ],
      inheritedFunctions: {
        owner:
          "lib/openzeppelin-contracts-upgradeable/contracts/access/OwnableUpgradeable.sol",
        renounceOwnership:
          "lib/openzeppelin-contracts-upgradeable/contracts/access/OwnableUpgradeable.sol",
        transferOwnership:
          "lib/openzeppelin-contracts-upgradeable/contracts/access/OwnableUpgradeable.sol",
        UPGRADE_INTERFACE_VERSION:
          "lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/UUPSUpgradeable.sol",
        proxiableUUID:
          "lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/UUPSUpgradeable.sol",
        upgradeToAndCall:
          "lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/UUPSUpgradeable.sol",
        onERC1155BatchReceived:
          "lib/openzeppelin-contracts/contracts/token/ERC1155/IERC1155Receiver.sol",
        onERC1155Received:
          "lib/openzeppelin-contracts/contracts/token/ERC1155/IERC1155Receiver.sol",
        supportsInterface:
          "lib/openzeppelin-contracts/contracts/token/ERC1155/IERC1155Receiver.sol",
      },
      deployedOnBlock: 11,
    },
  },
  19880818: {
    NFTStaking: {
      address: "0xd358641dbbc888a9c4976f82420682f777adc78f",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "BASE_RESERVE_AMOUNT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "LOCK_PERIOD",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_NFTS_PER_MACHINE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SECONDS_PER_BLOCK",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SLASH_AMOUNT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "STAKING_TYPE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum StakingType",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "UPGRADE_INTERFACE_VERSION",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "_getMachineShares",
          inputs: [
            {
              name: "calcPoint",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "reservedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "addTokenToStake",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "calculateReleaseReward",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "releaseAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lockedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "calculateRewards",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "canUpgradeAddress",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "dailyRewardAmount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "dbcAIContract",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IDBCAIContract",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "forceUnStake",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getAllRewardInfo",
          inputs: [
            {
              name: "holder",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "availableRewardAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "canClaimAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lockedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getMachineIdsByStakeholder",
          inputs: [
            {
              name: "holder",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string[]",
              internalType: "string[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getMachineInfo",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "holder",
              type: "address",
              internalType: "address",
            },
            {
              name: "calcPoint",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "startAtTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "reservedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isOnline",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "isRegistered",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getReward",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRewardInfo",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "newRewardAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "canClaimAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lockedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getStakeHolder",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getaCalcPoint",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "holder2MachineIds",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "initialize",
          inputs: [
            {
              name: "_initialOwner",
              type: "address",
              internalType: "address",
            },
            {
              name: "_nftToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "_rewardToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "_dbcAIContract",
              type: "address",
              internalType: "address",
            },
            {
              name: "_slashToAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_projectName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "isStaking",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isStakingButOffline",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineId2LockedRewardDetail",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "totalAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lockTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "unlockTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineId2LockedRewardDetails",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "totalAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lockTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "unlockTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineId2MachineStatus",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum MachineStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineId2StakeInfos",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "holder",
              type: "address",
              internalType: "address",
            },
            {
              name: "startAtTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastClaimAtTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "calcPoint",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "reservedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "nftCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "gpuCount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineId2StakeUnitRewards",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "accumulated",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastAccumulatedPerShare",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "machineIsBlocked",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nftToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC1155",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "onERC1155BatchReceived",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "onERC1155Received",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingSlashedMachine",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "preCalculateRewards",
          inputs: [
            {
              name: "calcPoint",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "nftCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "reserveAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "projectName",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "proxiableUUID",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rewardStartAtTimestamp",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rewardToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rewardsPerCalcPoint",
          inputs: [],
          outputs: [
            {
              name: "accumulatedPerShare",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastUpdated",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setDBCAIContract",
          inputs: [
            {
              name: "addr",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setDLCClientWallets",
          inputs: [
            {
              name: "addrs",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setNftToken",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setRewardStartAt",
          inputs: [
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setRewardToken",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setUpgradeAddress",
          inputs: [
            {
              name: "addr",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "slashToAddress",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "stake",
          inputs: [
            {
              name: "stakeholder",
              type: "address",
              internalType: "address",
            },
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
            {
              name: "nftTokenIds",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "nftTokenIdBalances",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stakedMachineIds",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "totalAdjustUnit",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalCalcPoint",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalDistributedRewardAmount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalGpuCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalReservedAmount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalStakingGpuCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "unStake",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "unStakeByHolder",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "upgradeToAndCall",
          inputs: [
            {
              name: "newImplementation",
              type: "address",
              internalType: "address",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "validWalletAddress",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "version",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "event",
          name: "Claimed",
          inputs: [
            {
              name: "stakeholder",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "lockedRewardAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "moveToUserWalletAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "moveToReservedAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "paidSlash",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ExitStakingForOffline",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "holder",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Initialized",
          inputs: [
            {
              name: "version",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MachineRegistered",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MachineUnregistered",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MoveToReserveAmount",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "holder",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PaySlash",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "slashAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RenewRent",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "holder",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "rentFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ReportMachineFault",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "renter",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ReserveDLC",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RewardsPerCalcPointUpdate",
          inputs: [
            {
              name: "accumulatedPerShareBefore",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "accumulatedPerShareAfter",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Staked",
          inputs: [
            {
              name: "stakeholder",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "originCalcPoint",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "calcPoint",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StakedGPUType",
          inputs: [
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "gpuType",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Unstaked",
          inputs: [
            {
              name: "stakeholder",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "machineId",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "paybackReserveAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Upgraded",
          inputs: [
            {
              name: "implementation",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AddressEmptyCode",
          inputs: [
            {
              name: "target",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "AddressExists",
          inputs: [],
        },
        {
          type: "error",
          name: "CallerNotRentContract",
          inputs: [],
        },
        {
          type: "error",
          name: "CanNotUpgrade",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC1967InvalidImplementation",
          inputs: [
            {
              name: "implementation",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC1967NonPayable",
          inputs: [],
        },
        {
          type: "error",
          name: "FailedCall",
          inputs: [],
        },
        {
          type: "error",
          name: "GPUTypeNotMatch",
          inputs: [
            {
              name: "gpuType",
              type: "string",
              internalType: "string",
            },
          ],
        },
        {
          type: "error",
          name: "InvalidInitialization",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidNFTLength",
          inputs: [
            {
              name: "tokenIdLength",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "balanceLength",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "IsStaking",
          inputs: [],
        },
        {
          type: "error",
          name: "MachineIsStaking",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
        },
        {
          type: "error",
          name: "MachineNotOnlineOrRegistered",
          inputs: [],
        },
        {
          type: "error",
          name: "MachineNotRented",
          inputs: [],
        },
        {
          type: "error",
          name: "MachineNotStakeEnoughDBC",
          inputs: [],
        },
        {
          type: "error",
          name: "MachineNotStaked",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
          ],
        },
        {
          type: "error",
          name: "MachineRentedByUser",
          inputs: [],
        },
        {
          type: "error",
          name: "MachineStillRegistered",
          inputs: [],
        },
        {
          type: "error",
          name: "MemorySizeLessThan16G",
          inputs: [
            {
              name: "mem",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "NFTCountGreaterThan20",
          inputs: [],
        },
        {
          type: "error",
          name: "NotAdmin",
          inputs: [],
        },
        {
          type: "error",
          name: "NotInitializing",
          inputs: [],
        },
        {
          type: "error",
          name: "NotMachineOwner",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "NotMachineOwnerOrAdmin",
          inputs: [],
        },
        {
          type: "error",
          name: "NotPaidSlashBeforeClaim",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
            {
              name: "slashAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "NotStakeHolder",
          inputs: [
            {
              name: "machineId",
              type: "string",
              internalType: "string",
            },
            {
              name: "currentAddress",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "RewardNotEnough",
          inputs: [],
        },
        {
          type: "error",
          name: "RewardNotStart",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "StakingInLongTerm",
          inputs: [],
        },
        {
          type: "error",
          name: "TimestampLessThanCurrent",
          inputs: [],
        },
        {
          type: "error",
          name: "TotalRateNotEq100",
          inputs: [],
        },
        {
          type: "error",
          name: "UUPSUnauthorizedCallContext",
          inputs: [],
        },
        {
          type: "error",
          name: "UUPSUnsupportedProxiableUUID",
          inputs: [
            {
              name: "slot",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroCalcPoint",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroNFTTokenIds",
          inputs: [],
        },
      ],
      inheritedFunctions: {
        owner:
          "lib/openzeppelin-contracts-upgradeable/contracts/access/OwnableUpgradeable.sol",
        renounceOwnership:
          "lib/openzeppelin-contracts-upgradeable/contracts/access/OwnableUpgradeable.sol",
        transferOwnership:
          "lib/openzeppelin-contracts-upgradeable/contracts/access/OwnableUpgradeable.sol",
        UPGRADE_INTERFACE_VERSION:
          "lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/UUPSUpgradeable.sol",
        proxiableUUID:
          "lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/UUPSUpgradeable.sol",
        upgradeToAndCall:
          "lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/UUPSUpgradeable.sol",
        onERC1155BatchReceived:
          "lib/openzeppelin-contracts/contracts/token/ERC1155/IERC1155Receiver.sol",
        onERC1155Received:
          "lib/openzeppelin-contracts/contracts/token/ERC1155/IERC1155Receiver.sol",
        supportsInterface:
          "lib/openzeppelin-contracts/contracts/token/ERC1155/IERC1155Receiver.sol",
      },
      deployedOnBlock: 3388726,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
