[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
fs_permissions = [{ access = "read-write", path = "./"}]
solc_version = "0.8.26"
ast = true
ffi = true
build_info = true
extra_output = ["storageLayout"]
viaIR = true
optimizer_runs = 200
eth_rpc_timeout = 300


[etherscan]
dbc-mainnet = { key = "abc", url = "https://rpc.dbcwallet.io", chain = "19880818" }
dbc-testnet = { key = "abc", url = "https://rpc-testnet.dbcwallet.io", chain = "19850818" }
local-testnet = { key = "abc", url = "http://localhost:7545", chain = "5777" }


[rpc_endpoints]
dbc-mainnet = "https://rpc2.dbcwallet.io"
dbc-testnet = "https://rpc-testnet.dbcwallet.io"
bsc-testnet = "https://data-seed-prebsc-1-s3.binance.org:8545"
local-testnet = { key = "abc", url = "http://localhost:7545", chain = "5777" }
localhost = "http://127.0.0.1:8545"
default_network = "http://127.0.0.1:8545"



[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"




# See more config options https://book.getfoundry.sh/reference/config/overview